### ISSUE TITLE
API Doesn't work

### ISSUE THREAD

**Issue by proxene** [uvulpos/simple-php-pterodactyl#1]
Hello,

After the execution of CURL we have a blank page and when we watch in the panel, in API KEY we see nothing in the column "Last Used" so I suppose that request doesn't work.

Can you fix your API ?

Thank you in advance.

Best regards,

**Comment by uvulpos** [comment]
Hello proxene,

Thank you for report your issue. Is the whole project not working or just some functions?

**Comment by proxene** [comment]
Hello thank you for your answer :-)

I think the problem comes from between the line 328 to 370 because I tried different functions and unfortunately nothing work.

**Comment by uvulpos** [comment]
Hey proxene,

I´m sorry to inform you that this will last longer than I thought. Got some issues on my server so I´ll inform you when I update my repository (probably on weekend) &#128516; Anyway have a nice day

**Comment by proxene** [comment]
Ok no problem :-)
Have a nice day you too

**Comment by uvulpos** [comment]
Hi it´s me again,

I tested my script again and I found some issues (like I said in README) but mainly it´s functional. Maybe someting in your config (constructor) is wrong. This is how my constructor looks like:
 
      $this->serverstuff = array(
        'serverhostname' => "https://subdomain.domain.de/"
       ,'serverpassword' => "" // Admin-Token NOT User-Token that could be the issue
      );

and there we have my execute-file:

    require_once "gamewebinterface.php";
    $newPterodatylinstanz = new ownPterodactylClass(true);
    print_r($newPterodatylinstanz->createServer("", "", "", ""));

I hope this helps if not... I don´t know either 

Anyway good look with your project  &#128516;
~ uVulpos
